// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

import {
  nsZenPreloadedFeature,
  nsZenMultiWindowFeature,
} from "chrome://browser/content/zen-components/ZenCommonUtils.mjs";

// Chromium migration (lane 3): prefs + storage + session via adapters.
// Gecko: Services.prefs / IOUtils+PathUtils / SessionStore / Cc[nsIZenModsBackend].
// Chromium: chrome.storage / chrome.storage.local(+downloads) / chrome.sessions /
// chrome.scripting (see src/zen/adapters/prefs.mjs, adapters/storage.mjs,
// adapters/session.mjs). chrome:// import below becomes a shared/ module.
import {
  getBoolPref,
  getIntPref,
  getStringPref,
  setBoolPref,
  setIntPref,
  setStringPref,
} from "../adapters/prefs.mjs";
import {
  joinPath,
  getProfileDir,
  makeDirectory,
  pathExists,
  readUTF8,
  writeUTF8,
} from "../adapters/storage.mjs";

const DOT_RE = /\./g;
const WHITESPACE_RE = /\s/g;
const NON_NAME_RE = /[^A-Za-z_-]+/g;

/**
 * Zen Mods Manager, handles downloading, updating and applying Zen Mods.
 *
 * @augments nsZenPreloadedFeature
 */
class nsZenMods extends nsZenPreloadedFeature {
  // private properties start
  #kZenStylesheetModHeader = "/* Zen Mods - Generated by ZenMods.";
  #kZenStylesheetModHeaderBody = `* DO NOT EDIT THIS FILE DIRECTLY!
* Your changes will be overwritten.
* Instead, go to the preferences and edit the mods there.
*/
`;
  #kZenStylesheetModFooter = `
/* End of Zen Mods */
`;
  #getCurrentDateTime = () =>
    new Intl.DateTimeFormat("en-US", {
      dateStyle: "full",
      timeStyle: "full",
    }).format(new Date().getTime());

  constructor() {
    super();
  }

  // Stylesheet service
  #_modsBackend = null;

  get #modsBackend() {
    // Chromium: chrome.scripting backend; nsIZenModsBackend XPCOM is Gecko-only.
    if (!this.#_modsBackend) {
      this.#_modsBackend = Cc["@mozilla.org/zen/mods-backend;1"].getService(
        Ci.nsIZenModsBackend
      );
    }
    return this.#_modsBackend;
  }

  get #styleSheetPath() {
    return joinPath(getProfileDir(), "chrome", "zen-themes.css");
  }

  async #handleDisableMods() {
    await this.#rebuildModsStylesheet();
  }

  #getStylesheetPathForMod(mod) {
    return joinPath(this.getModFolder(mod.id), "chrome.css");
  }

  async #readStylesheet() {
    const path = this.modsRootPath;
    if (!(await pathExists(path))) {
      return "";
    }
    return await readUTF8(this.#styleSheetPath);
  }

  async #insertStylesheet() {
    try {
      const content = await this.#readStylesheet();
      this.#modsBackend.rebuildModsStyles(content);
    } catch (e) {
      console.warn("[ZenMods]: Error rebuilding mods styles:", e);
    }
  }

  async #rebuildModsStylesheet() {
    const mods = await this.#getEnabledMods();

    await this.#writeStylesheet(mods);

    const modsWithPreferences = await Promise.all(
      mods.map(async mod => {
        const preferences = await this.getModPreferences(mod);

        return {
          name: mod.name,
          enabled: mod.enabled,
          preferences,
        };
      })
    );

    this.#setDefaults(modsWithPreferences);
    this.#writeToDom(modsWithPreferences);

    await this.#insertStylesheet();
  }

  async #getEnabledMods() {
    if (getBoolPref("zen.themes.disable-all", false)) {
      // eslint-disable-next-line no-console
      console.info("[ZenMods]: Mods are disabled by user preference.");
      return [];
    }
    const modsObject = await this.getMods();
    const mods = Object.values(modsObject).filter(
      mod => mod.enabled === undefined || mod.enabled
    );

    // eslint-disable-next-line no-shadow
    const modList = mods.map(({ name }) => name).join(", ");

    const message =
      modList !== ""
        ? `[ZenMods]: Loading enabled Zen mods: ${modList}.`
        : "[ZenMods]: No enabled Zen mods.";

    console.warn(message);

    return mods;
  }

  #setDefaults(modsWithPreferences) {
    for (const { preferences, enabled } of modsWithPreferences) {
      if (enabled !== undefined && !enabled) {
        continue;
      }

      for (const { type, property, defaultValue } of preferences) {
        if (defaultValue === undefined) {
          continue;
        }

        // Chromium: same getter/setter shape, backed by chrome.storage (see adapters/prefs.mjs).
        const getProperty =
          type === "checkbox" ? getBoolPref : getStringPref;
        const setProperty =
          type === "checkbox" ? setBoolPref : setStringPref;

        try {
          getProperty(property);
        } catch {
          console.warn(
            `[ZenMods]: Setting default value for ${property} to ${defaultValue} (${typeof defaultValue})`
          );

          if (
            typeof defaultValue !== "boolean" &&
            typeof defaultValue !== "string" &&
            typeof defaultValue !== "number"
          ) {
            console.warn(
              `[ZenMods]: Warning, invalid data type received (${typeof defaultValue}), skipping.`
            );
            continue;
          }

          setProperty(
            property,
            typeof defaultValue === "boolean"
              ? defaultValue
              : defaultValue.toString()
          );
        }
      }
    }
  }

  #writeToDom(modsWithPreferences) {
    // Precompute per-mod data once; values are global prefs and sanitized
    // names don't vary per browser window, so this hoists O(windows) work.
    const prepared = modsWithPreferences.map(
      // eslint-disable-next-line no-shadow
      ({ enabled, preferences, name }) => ({
        enabled,
        sanitizedName: this.sanitizeModName(name),
        prefs: preferences.map(({ property, type }) => ({
          property,
          type,
          sanitizedProperty: property?.replaceAll(DOT_RE, "-"),
          value:
            enabled === undefined || enabled
              ? getStringPref(property, "")
              : "",
        })),
      })
    );

    for (const browser of nsZenMultiWindowFeature.browsers) {
      const doc = browser.document;
      const root = doc.documentElement;

      for (const { enabled, sanitizedName, prefs } of prepared) {
        if (enabled !== undefined && !enabled) {
          const element = doc.getElementById(sanitizedName);
          if (element) {
            element.remove();
          }

          for (const { type, sanitizedProperty } of prefs) {
            if (type === "checkbox") {
              continue;
            }
            root.style.removeProperty(`--${sanitizedProperty}`);
          }

          continue;
        }

        for (const { type, sanitizedProperty, value } of prefs) {
          switch (type) {
            case "dropdown": {
              if (value !== "") {
                let element = doc.getElementById(sanitizedName);

                if (!element) {
                  element = doc.createElement("div");
                  element.style.display = "none";
                  element.setAttribute("id", sanitizedName);
                  doc.body.appendChild(element);
                }

                element.setAttribute(sanitizedProperty, value);
              }
              break;
            }

            case "string": {
              if (value === "") {
                root.style.removeProperty(`--${sanitizedProperty}`);
              } else {
                root.style.setProperty(`--${sanitizedProperty}`, value);
              }
              break;
            }
          }
        }
      }
    }
  }

  async #writeStylesheet(modList = []) {
    const mods = [];

    for (let mod of modList) {
      mod._filePath = this.#getStylesheetPathForMod(mod);
      mods.push(mod);
    }

    let content = this.#kZenStylesheetModHeader;
    content += `\n* FILE GENERATED AT: ${this.#getCurrentDateTime()}\n`;
    content += this.#kZenStylesheetModHeaderBody;

    for (let mod of mods) {
      if (mod.enabled !== undefined && !mod.enabled) {
        continue;
      }

      content += `\n/* Name: ${mod.name} */\n`;
      content += `/* Description: ${mod.description} */\n`;
      content += `/* Author: @${mod.author} */\n`;

      if (mod._readmeURL) {
        content += `/* Readme: ${mod.readme} */\n`;
      }

      // Chromium: readUTF8()/writeUTF8() via adapters/storage.mjs.
      const chromeContent = await readUTF8(mod._filePath);
      content += chromeContent;
    }

    content += this.#kZenStylesheetModFooter;

    const buffer = new TextEncoder().encode(content);

    await writeUTF8(this.#styleSheetPath, buffer);
  }

  #compareVersions(version1, version2) {
    let result = false;

    if (typeof version1 !== "object") {
      version1 = version1.toString().split(".");
    }

    if (typeof version2 !== "object") {
      version2 = version2.toString().split(".");
    }

    for (let i = 0; i < Math.max(version1.length, version2.length); i++) {
      if (version1[i] == undefined) {
        version1[i] = 0;
      }
      if (version2[i] == undefined) {
        version2[i] = 0;
      }
      if (Number(version1[i]) < Number(version2[i])) {
        result = true;
        break;
      }
      if (version1[i] != version2[i]) {
        break;
      }
    }
    return result;
  }

  #composeModApiUrl(modId) {
    // keeping theme here as it would require changes to CI to change the name
    return `https://zen-browser.github.io/theme-store/themes/${modId}/theme.json`;
  }

  async #downloadUrlToFile(url, path, maxRetries = 3, retryDelayMs = 500) {
    // Mod assets must come over HTTPS. Without a signing/hash scheme this
    // is the minimum guard against MITM or a store-hosted HTTP redirect
    // serving attacker-controlled CSS/JSON into the chrome profile.
    let parsed;
    try {
      parsed = new URL(url);
    } catch {
      throw new Error(`[ZenMods]: Invalid mod asset URL: ${url}`);
    }
    if (parsed.protocol !== "https:") {
      throw new Error(`[ZenMods]: Refusing non-HTTPS mod asset URL: ${url}`);
    }

    let attempt = 0;

    while (attempt < maxRetries) {
      try {
        const response = await fetch(url);

        if (!response.ok) {
          throw new Error(
            `HTTP error! status: ${response.status} for url: ${url}`
          );
        }

        const data = await response.text();

        // convert the data into a Uint8Array
        const buffer = new TextEncoder().encode(data);
        // Chromium: writeUTF8() / chrome.downloads; IOUtils.write is Gecko-only.
        await IOUtils.write(path, buffer);

        return; // to exit the loop
      } catch (e) {
        attempt++;
        if (attempt >= maxRetries) {
          console.error(
            "[ZenMods]: Error downloading file after retries",
            url,
            e
          );
        } else {
          console.warn(
            `[ZenMods]: Download failed (attempt ${attempt} of ${maxRetries}), retrying in ${retryDelayMs}ms...`,
            url,
            e
          );
          await new Promise(res => setTimeout(res, retryDelayMs));
        }
      }
    }
  }

  // private properties end

  // public properties start

  throttle(mainFunction, delay) {
    let timerFlag = null;

    return (...args) => {
      if (timerFlag === null) {
        mainFunction(...args);
        timerFlag = setTimeout(() => {
          timerFlag = null;
        }, delay);
      }
    };
  }

  debounce(mainFunction, wait) {
    let timerFlag;

    return (...args) => {
      clearTimeout(timerFlag);
      timerFlag = setTimeout(() => {
        mainFunction(...args);
      }, wait);
    };
  }

  sanitizeModName(aName) {
    // Do not change to "mod-" for backwards compatibility
    return `theme-${aName?.replaceAll(WHITESPACE_RE, "-")?.replaceAll(NON_NAME_RE, "")}`;
  }

  get updatePref() {
    return "zen.mods.updated-value-observer";
  }

  get modsRootPath() {
    return joinPath(getProfileDir(), "chrome", "zen-themes");
  }

  get modsDataFile() {
    return joinPath(getProfileDir(), "zen-themes.json");
  }

  getModFolder(modId) {
    return joinPath(this.modsRootPath, modId);
  }

  async getMods() {
    // Chromium: chrome.storage.local JSON doc; IOUtils JSON helpers are Gecko-only.
    if (!(await IOUtils.exists(this.modsDataFile))) {
      await IOUtils.writeJSON(this.modsDataFile, {});

      return {};
    }

    let mods = {};

    try {
      mods = await IOUtils.readJSON(this.modsDataFile);

      if (mods === null || typeof mods !== "object") {
        throw new Error("Mods data file is invalid");
      }
    } catch {
      // If we have a corrupted file, reset it
      await IOUtils.writeJSON(this.modsDataFile, {});

      // Chromium: chrome.windows.getLastFocused + extension toast; Services.wm is Gecko-only.
      Services.wm
        .getMostRecentWindow("navigator:browser")
        .gZenUIManager.showToast("zen-themes-corrupted", {
          timeout: 8000,
        });
    }

    return mods;
  }

  async getModPreferences(mod) {
    // Chromium: chrome.storage.local JSON doc; IOUtils JSON helpers are Gecko-only.
    const modPath = joinPath(this.modsRootPath, mod.id, "preferences.json");

    if (!(await pathExists(modPath)) || !mod.preferences) {
      return [];
    }

    try {
      const preferences = await IOUtils.readJSON(modPath);

      return preferences.filter(({ disabledOn = [] }) => {
        return !disabledOn.includes(
          gZenOperatingSystemCommonUtils.currentOperatingSystem
        );
      });
    } catch (e) {
      console.error(
        `[ZenMods]: Error reading mod preferences for ${mod.name}:`,
        e
      );
      return [];
    }
  }

  async init() {
    try {
      // Chromium: getAllWindowsRestoredPromise() / chrome.sessions (see adapters/session.mjs).
      await SessionStore.promiseInitialized;

      if (
        getBoolPref("zen.themes.disable-all", false) ||
        Services.appinfo.inSafeMode
      ) {
        console.warn("[ZenMods]: Mods disabled by user or in safe mode.");
        return;
      }

      await this.getMods(); // Check for any errors in the themes data file
      const mods = await this.#getEnabledMods();

      const modsWithPreferences = await Promise.all(
        mods.map(async mod => {
          const preferences = await this.getModPreferences(mod);

          return {
            name: mod.name,
            enabled: mod.enabled,
            preferences,
          };
        })
      );

      this.#writeToDom(modsWithPreferences);

      await this.#insertStylesheet();

      this.#setNewMilestoneIfNeeded();
      if (this.#shouldAutoUpdate()) {
        requestIdleCallback(
          () => {
            if (!window.closed) {
              requestAnimationFrame(() => {
                this.checkForModsUpdates();
              });
            }
          },
          { timeout: 1000 }
        );
      }
    } catch (e) {
      console.error("[ZenMods]: Error loading Zen Mods:", e);
    }

    // Chromium: chrome.storage.onChanged; Services.prefs.addObserver is Gecko-only.
    Services.prefs.addObserver(
      this.updatePref,
      this.#rebuildModsStylesheet.bind(this)
    );
    // Chromium: chrome.storage.onChanged; Services.prefs.addObserver is Gecko-only.
    Services.prefs.addObserver(
      "zen.themes.disable-all",
      this.#handleDisableMods.bind(this)
    );
  }

  #setNewMilestoneIfNeeded() {
    const previousMilestone = getStringPref("zen.mods.milestone", "");
    if (previousMilestone != Services.appinfo.version) {
      setStringPref("zen.mods.milestone", Services.appinfo.version);
      // Chromium: chrome.storage.local.remove(); clearUserPref is Gecko-only.
      Services.prefs.clearUserPref("zen.mods.last-update");
    }
  }

  #shouldAutoUpdate() {
    const daysBeforeUpdate = getIntPref("zen.mods.auto-update-days", 7);
    const lastUpdatedSec = getIntPref("zen.mods.last-update", -1);
    const nowSec = Math.floor(Date.now() / 1000);
    const daysSinceUpdate = (nowSec - lastUpdatedSec) / (60 * 60 * 24);

    return (
      (getBoolPref("zen.mods.auto-update", true) &&
        daysSinceUpdate >= daysBeforeUpdate) ||
      lastUpdatedSec < 0
    );
  }

  async checkForModsUpdates() {
    const mods = await this.getMods();

    const updates = await Promise.all(
      Object.values(mods).map(async currentMod => {
        try {
          const possibleNewModVersion = await this.requestMod(currentMod.id);

          if (!possibleNewModVersion) {
            return null;
          }

          if (
            !this.#compareVersions(
              possibleNewModVersion.version,
              currentMod.version ?? "0.0.0"
            ) &&
            possibleNewModVersion.version != currentMod.version
          ) {
            console.warn(
              `[ZenMods]: Mod update found for mod ${currentMod.name} (${currentMod.id}), current: ${currentMod.version}, new: ${possibleNewModVersion.version}`
            );

            possibleNewModVersion.enabled = currentMod.enabled;

            await this.removeMod(currentMod.id, false);

            mods[currentMod.id] = possibleNewModVersion;

            return possibleNewModVersion;
          }

          return null;
        } catch (e) {
          console.error("[ZenMods]: Error checking for mod updates", e);

          return null;
        }
      })
    );

    await this.updateMods(mods);
    setIntPref("zen.mods.last-update", Math.floor(Date.now() / 1000));
    return updates.filter(update => {
      return update !== null;
    });
  }

  async removeMod(modId, triggerUpdate = true) {
    const modPath = this.getModFolder(modId);

    console.warn(`[ZenMods]: Removing mod ${modPath}`);

    // Chromium: removePath() / chrome.storage.local; IOUtils.remove is Gecko-only.
    await IOUtils.remove(modPath, { recursive: true, ignoreAbsent: true });

    const mods = await this.getMods();

    delete mods[modId];

    await IOUtils.writeJSON(this.modsDataFile, mods);

    if (triggerUpdate) {
      this.triggerModsUpdate();
    }
  }

  async enableMod(modId) {
    const mods = await this.getMods();
    const mod = mods[modId];

    console.warn(`[ZenMods]: Enabling mod ${mod.name}`);

    mod.enabled = true;

    await IOUtils.writeJSON(this.modsDataFile, mods);
  }

  async disableMod(modId) {
    const mods = await this.getMods();
    const mod = mods[modId];

    console.warn(`[ZenMods]: Disabling mod ${mod.name}`);

    mod.enabled = false;

    await IOUtils.writeJSON(this.modsDataFile, mods);
  }

  async updateMods(mods = undefined) {
    if (!mods) {
      mods = await this.getMods();
    }

    await IOUtils.writeJSON(this.modsDataFile, mods);
    await this.checkForModChanges();
  }

  triggerModsUpdate() {
    // Chromium: setBoolPref()/getBoolPref() toggle the update observer pref.
    setBoolPref(this.updatePref, !getBoolPref(this.updatePref, false));
  }

  async installMod(mod) {
    // Chromium: chrome.storage.local + chrome.downloads; IOUtils/PathUtils are Gecko-only.
    try {
      const modPath = joinPath(this.modsRootPath, mod.id);
      await makeDirectory(modPath, { ignoreExisting: true });

      await this.#downloadUrlToFile(mod.style, joinPath(modPath, "chrome.css"));
      await this.#downloadUrlToFile(mod.readme, joinPath(modPath, "readme.md"));

      if (mod.preferences) {
        await this.#downloadUrlToFile(
          mod.preferences,
          joinPath(modPath, "preferences.json")
        );
      }
    } catch (e) {
      console.error("[ZenMods]: Error installing mod", mod.id, e);
    }
  }

  async checkForModChanges() {
    const mods = await this.getMods();

    for (const [modId, mod] of Object.entries(mods)) {
      try {
        if (!mod) {
          continue;
        }

        // Chromium: pathExists() via adapters/storage.mjs.
        if (!(await pathExists(this.getModFolder(modId)))) {
          await this.installMod(mod);
        }
      } catch (e) {
        console.error("[ZenMods]: Error checking for mod changes", e);
      }
    }

    this.triggerModsUpdate();
  }

  async requestMod(modId) {
    const url = this.#composeModApiUrl(modId);

    console.warn(`[ZenMods]: Fetching mod ${modId} info from ${url}`);

    const data = await fetch(url, {
      mode: "no-cors",
    });

    if (data.ok) {
      try {
        const obj = await data.json();

        return obj;
      } catch (e) {
        console.error(`[ZenMods]: Error parsing mod ${modId} info:`, e);
      }
    } else {
      console.error(
        `[ZenMods]: Error fetching mod ${modId} info:`,
        data.status
      );
    }

    return null;
  }

  async isModInstalled(modId) {
    const mods = await this.getMods();
    return Boolean(mods?.[modId]);
  }

  // public properties end
}

window.gZenMods = new nsZenMods();
